kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "custom-build"
  namespace: kbit
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/kbit-ui"
  strategy:
    customStrategy:
      from:
        kind: "DockerImage"
        name: "dimssss/custom-builder:31"