apiVersion: v1
kind: Secret
metadata:
  name: "builder-config"
  namespace: "chuck-ops"
type: Opaque
stringData:
  master_url: "https://api.a.okto.ocplab.io:6443"
  user: "builder"
  password: "password"
  ops_project: "kbit"
  app_project: "kbit"