kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "ui"
  namespace: "kbit"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/kbit-ui"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "nodejs:latest"
        namespace: openshift
  output:
    to:
      kind: "ImageStreamTag"
      name: "kbit-ui:latest"
      namespace: "kbit"
  triggers:
  - github:
      secret: dGvu1slX2WybtV_HOcYJ
    type: "GitHub"